org.gradle.jvmargs=-Xmx4G -Djavax.net.ssl.trustStore=gradle/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit

# Architectury / MC
minecraft_version=1.21.11
enabled_platforms=fabric

# Mod
mod_id=mcms
mod_name=MCMS
mod_description=在游戏内深度接入 MCMS 城市管理系统的客户端模组
mod_author=mcms-mod
mod_license=MIT
archives_base_name=mcms
mod_version=0.1.0
maven_group=hk.flynt

# Architectury
architectury_version=19.0.1
loom_version=1.13-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.141.6+1.21.11